In [1]:
pip install scikit-Image

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
pip install -U scikit-learn

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
import os
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from skimage import io, transform
import numpy as np

# Ganti dengan direktori yang berisi folder dataset
dataset_dir = 'D:\ML\datasetball'

# Inisialisasi daftar kelas dan label
classes = ['Billiard', 'Football', 'Table Tennis']
labels = [0, 1, 2]

X_train = []
y_train = []

# Load data training
for label, class_name in zip(labels, classes):
    class_dir = os.path.join(dataset_dir, class_name)
    
    # Untuk setiap gambar dalam kelas
    for image_name in os.listdir(class_dir):
        image_path = os.path.join(class_dir, image_name)
        
        # Ubah gambar menjadi ukuran yang sama
        image = io.imread(image_path, as_gray=True)
        image = transform.resize(image, (100, 100))  # Ubah ukuran gambar menjadi 100x100
        
        # Ubah gambar menjadi larik nilai piksel
        image_flattened = image.flatten()
        
        # Tambahkan gambar dan label kelas ke data training
        X_train.append(image_flattened)
        y_train.append(label)

X_train = np.array(X_train)
y_train = np.array(y_train)

print("Data Training (X_train):")
print(X_train)
print("Label Training (y_train):")
print(y_train)

# Inisialisasi model SVM
svm = SVC()

# Latih model SVM menggunakan data training
svm.fit(X_train, y_train)

# Inisialisasi model KNN
knn = KNeighborsClassifier()

# Latih model KNN menggunakan data training
knn.fit(X_train, y_train)

# Load data testing
X_test = []
y_test = []
test_dir = r'D:\ML\train'

# Untuk setiap gambar dalam folder testing
for image_name in os.listdir(test_dir):
    image_path = os.path.join(test_dir, image_name)
    
    # Ubah gambar menjadi ukuran yang sama
    image = io.imread(image_path, as_gray=True)
    image = transform.resize(image, (100, 100))  # Ubah ukuran gambar menjadi 100x100
    
    # Ubah gambar menjadi larik nilai piksel
    image_flattened = image.flatten()
    
    # Tambahkan gambar dan label kelas ke data testing
    X_test.append(image_flattened)
    # Tambahkan label dummy karena tidak diketahui
    y_test.append(-1)

X_test = np.array(X_test)
y_test = np.array(y_test)

# Prediksi kelas dari data testing menggunakan model SVM
y_pred_svm = svm.predict(X_test)

# Cetak hasil prediksi menggunakan model SVM
print("Hasil Prediksi (SVM):")
for i, pred in enumerate(y_pred_svm):
    class_name = classes[pred]
    print("Gambar", i+1, ": Prediksi =", class_name)

# Prediksi kelas dari data testing menggunakan model KNN
y_pred_knn = knn.predict(X_test)

# Cetak hasil prediksi menggunakan model KNN
print("Hasil Prediksi (KNN):")
for i, pred in enumerate(y_pred_knn):
    class_name = classes[pred]
    print("Gambar", i+1, ": Prediksi= ", class_name)

# Evaluasi akurasi model SVM
y_train_pred_svm = svm.predict(X_train)
train_accuracy_svm = accuracy_score(y_train, y_train_pred_svm)
print("Akurasi Model SVM (Data Training):", train_accuracy_svm)

# Evaluasi akurasi model KNN
y_train_pred_knn = knn.predict(X_train)
train_accuracy_knn = accuracy_score(y_train, y_train_pred_knn)
print("Akurasi Model KNN (Data Training):", train_accuracy_knn)

<>:9: SyntaxWarning: invalid escape sequence '\M'
<>:9: SyntaxWarning: invalid escape sequence '\M'
C:\Users\User\AppData\Local\Temp\ipykernel_16096\3748894563.py:9: SyntaxWarning: invalid escape sequence '\M'
  dataset_dir = 'D:\ML\datasetball'


Data Training (X_train):
[[0.07481881 0.0749797  0.07556365 ... 0.34860346 0.14937409 0.11981551]
 [1.         1.         1.         ... 1.         1.         1.        ]
 [0.01466073 0.0146607  0.01450815 ... 0.19177008 0.18178492 0.18297374]
 ...
 [1.         1.         1.         ... 1.         1.         1.        ]
 [0.14357775 0.13945494 0.12901477 ... 0.24953092 0.24138823 0.23062418]
 [1.         1.         1.         ... 1.         1.         1.        ]]
Label Training (y_train):
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 